// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGn-rOQHiZcQohq5kNcq0_66WwmZT6jtM',
    appId: '1:306740350288:web:9ea7cf77457ead6fdcb055',
    messagingSenderId: '306740350288',
    projectId: 'notewise-2b046',
    authDomain: 'notewise-2b046.firebaseapp.com',
    storageBucket: 'notewise-2b046.appspot.com',
    measurementId: 'G-ESCGWVJEQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2HB7Gp8NM6cLqj7V5-Tf2mQ773U9SKvM',
    appId: '1:306740350288:android:440042f988b550d6dcb055',
    messagingSenderId: '306740350288',
    projectId: 'notewise-2b046',
    storageBucket: 'notewise-2b046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-UbhTc8Y2nwU-aMBxuJWcjorFokxuVg',
    appId: '1:306740350288:ios:a89251e3d719134cdcb055',
    messagingSenderId: '306740350288',
    projectId: 'notewise-2b046',
    storageBucket: 'notewise-2b046.appspot.com',
    iosClientId: '306740350288-camfmq4kibr13803omo92il0oje7v4ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.notewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-UbhTc8Y2nwU-aMBxuJWcjorFokxuVg',
    appId: '1:306740350288:ios:449b54541b416379dcb055',
    messagingSenderId: '306740350288',
    projectId: 'notewise-2b046',
    storageBucket: 'notewise-2b046.appspot.com',
    iosClientId: '306740350288-6t21ivup8ro2fm5f22nc1ismundftaem.apps.googleusercontent.com',
    iosBundleId: 'com.example.notewise.RunnerTests',
  );
}
